-- CRIA A BASE DE DADOS --
CREATE DATABASE DB_1DS3_2;

-- SELECIONA A BASE QUE IRÁ SER USADA --
USE DB_1DS3_2;

CREATE TABLE TB_DISCIPLINA(
  CD_DISCIPLINA INT,
  NM_DISCIPLINA VARCHAR(45),
  SG_DISCIPLINA VARCHAR(10),
  PRIMARY KEY(CD_DISCIPLINA)
);

CREATE TABLE TB_ALUNO(
  CD_ALUNO INT,
  NM_ALUNO VARCHAR(45),
  NM_EMAIL VARCHAR(45),
  DT_NASCIMENTO DATE,
  IC_SEXO CHAR(1),
  PRIMARY KEY(CD_ALUNO),
  CONSTRAINT EMAIL_ALUNO_UNICO UNIQUE(NM_EMAIL)
);

CREATE TABLE TB_TURMA(
  CD_TURMA INT,
  ID_DISCIPLINA INT,
  ID_ALUNO INT,
  SG_TURMA VARCHAR(5),
  PRIMARY KEY(CD_TURMA),
  CONSTRAINT ALUNO_FK
  FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNO(CD_ALUNO),
  CONSTRAINT DISCIPLINA_FK
  FOREIGN KEY(ID_DISCIPLINA) REFERENCES TB_DISCIPLINA(CD_DISCIPLINA)
);

CREATE TABLE TB_TELEFONE(
  CD_TELEFONE INT,
  CD_DDD CHAR(2),
  NR_TELEFONE VARCHAR(11),
  ID_ALUNO INT,
  PRIMARY KEY(CD_TELEFONE),
  CONSTRAINT FONE_ALUNO_FK
  FOREIGN KEY(ID_ALUNO) REFERENCES TB_ALUNO(CD_ALUNO)
);

-- INDEXES TB_TURMA
-- ALUNO_FK
-- DISCIPLINA_FK

-- INDEXES TB_ALUNO
-- EMAIL_ALUNO_UNICO

-- INDEXES TB_TELEFONE
-- FONE_ALUNO_FK