-- SELECIONA A BASE QUE IRÁ SER USADA --
CREATE DATABASE lojadecarro;
USE lojadecarro;

CREATE TABLE TB_FORNECEDOR(
  CD_FORNECEDOR INT AUTO_INCREMENT,
  NM_FORNECEDOR VARCHAR(50),
  ENDERECO VARCHAR(50),
  OUTROS VARCHAR(50),
  PRIMARY KEY(CD_FORNECEDOR)
);

CREATE TABLE TB_MARCA(
  CD_MARCA INT AUTO_INCREMENT,
  NM_MARCA VARCHAR(50),
  PRIMARY KEY(CD_MARCA)
);

CREATE TABLE TB_CLIENTE(
  CD_CLIENTE INT AUTO_INCREMENT,
  NM_CLIENTE VARCHAR(50),
  PRIMARY KEY(CD_CLIENTE)
);

CREATE TABLE TB_MODELO(
  CD_MODELO INT AUTO_INCREMENT,
  NM_MODELO VARCHAR(50),
  ID_MARCA INT,
  PRIMARY KEY(CD_MODELO),
  CONSTRAINT MARCA_FK FOREIGN KEY(ID_MARCA) REFERENCES TB_MARCA(CD_MARCA)
);

CREATE TABLE TB_COR(
  CD_COR INT AUTO_INCREMENT,
  TP_COR VARCHAR(50),
  PRIMARY KEY(CD_COR)
);

CREATE TABLE TB_VEICULO(
  CD_VEICULO INT AUTO_INCREMENT,
  DESCRICAO VARCHAR(50),
  OUTROSS VARCHAR(50),
  ID_MODELO INT,
  ID_COR INT,
  PRIMARY KEY(CD_VEICULO),
  CONSTRAINT MODELO_FK FOREIGN KEY(ID_MODELO)
  REFERENCES TB_MODELO(CD_MODELO),
  CONSTRAINT COR_FK FOREIGN KEY(ID_COR)
  REFERENCES TB_COR(CD_COR)
);

CREATE TABLE TB_CONTRATO(
  CD_CONTRATO INT AUTO_INCREMENT,
  DT_CONTRATO date,
  VL_DIARIA DECIMAL (10,2),
  VL_SEGURO DECIMAL(10,2) ,
  ID_VEICULO INT,
  ID_CLIENTE INT,
  PRIMARY KEY(CD_CONTRATO),
  CONSTRAINT VEICULO_FK FOREIGN KEY(ID_VEICULO)
  REFERENCES TB_VEICULO(CD_VEICULO),
  CONSTRAINT CLIENTE_FK FOREIGN KEY(ID_CLIENTE)
  REFERENCES TB_CLIENTE(CD_CLIENTE)
);

CREATE TABLE TB_MANUTENCAO(
  CD_MANUTENCAO INT AUTO_INCREMENT,
  VL_MANUTENCAO DECIMAL(6, 2),
  ID_VEICULO INT,
  DT_MANUTENCAO VARCHAR(50),
  PRIMARY KEY(CD_MANUTENCAO),
  CONSTRAINT VEICULOO_FK FOREIGN KEY(ID_VEICULO)
  REFERENCES TB_VEICULO(CD_VEICULO)
);