-- CRIA A BASE DE DADOS --
CREATE DATABASE DB_1DS3;

-- SELECIONA A BASE QUE IRÁ SER USADA --
USE DB_1DS3;

CREATE TABLE TB_CATEGORIA(
  CD_CATEGORIA INT AUTO_INCREMENT,
  NM_CATE VARCHAR(50),
  PRIMARY KEY(CD_CATEGORIA)
);

CREATE TABLE TB_CLIENTE(
  CD_CLIENTE INT AUTO_INCREMENT,
  NM_CLIENTE VARCHAR(50),
  CPF VARCHAR(11),
  PRIMARY KEY(CD_CLIENTE)
);

CREATE TABLE TB_PRODUTO(
  CD_PRODUTO INT AUTO_INCREMENT,
  ID_CATEGORIA INT,
  NM_PRO VARCHAR(50),
  DS_DESCRICAO DECIMAL(9, 2),
  QT_QUANTIDADE INT,
  PRIMARY KEY(CD_PRODUTO),
  CONSTRAINT CATEGORIA_FK FOREIGN KEY(ID_CATEGORIA)
  REFERENCES TB_CATEGORIA(CD_CATEGORIA)
);

CREATE TABLE TB_VENDA(
  CD_VENDA INT AUTO_INCREMENT,
  DT_VENDA DATE,
  TOTAL_VENDA DECIMAL(9, 2),
  ID_CLIENTE INT,
  PRIMARY KEY(CD_VENDA)
);

CREATE TABLE ITEM_VENDA(
  QT_QUANTIDADE INT,
  VL_PRECO_UNIT DECIMAL(9, 2),
  ID_VENDA INT,
  ID_PRODUTO INT,
  CONSTRAINT VENDA_FK FOREIGN KEY(ID_VENDA)
  REFERENCES TB_VENDA(CD_VENDA),
  CONSTRAINT PRODUTO_FK FOREIGN KEY(ID_PRODUTO)
  REFERENCES TB_PRODUTO(CD_PRODUTO)
);