CREATE DATABASE biblioteca;
USE biblioteca;

CREATE TABLE TB_GENERO(
  CD_GENERO INT AUTO_INCREMENT,
  NM_GENERO VARCHAR(50),
  PRIMARY KEY(CD_GENERO)
);

CREATE TABLE TB_PUBLICACAO(
  CD_PUBLICACAO INT AUTO_INCREMENT,
  ISBN VARCHAR(50),
  TITULO VARCHAR(50),
  ID_GENERO INT,
  PRIMARY KEY(CD_PUBLICACAO),
  CONSTRAINT GENERO_FK FOREIGN KEY(ID_GENERO)
  REFERENCES TB_GENERO(CD_GENERO)
);

CREATE TABLE TB_PRATELEIRA(
  CD_PRATELEIRA INT AUTO_INCREMENT,
  LOCALIZACAO VARCHAR(50),
  ID_GENERO INT,
  PRIMARY KEY(CD_PRATELEIRA),
  CONSTRAINT GENEROO_FK FOREIGN KEY(ID_GENERO)
  REFERENCES TB_GENERO(CD_GENERO)
);

CREATE TABLE TB_EXEMPLAR(
  CD_EXEMPLAR INT AUTO_INCREMENT,
  ID_PUBLICACAO INT,
  PRIMARY KEY(CD_EXEMPLAR),
  CONSTRAINT PUBLICACAO_FK FOREIGN KEY(ID_PUBLICACAO)
  REFERENCES TB_PUBLICACAO(CD_PUBLICACAO)
);

CREATE TABLE TB_UNIDADE(
  CD_UNIDADE INT AUTO_INCREMENT,
  NM_UNIDADE VARCHAR(50),
  PRIMARY KEY(CD_UNIDADE)
);

CREATE TABLE TB_COLABORADOR(
  CD_COLABORADOR INT AUTO_INCREMENT,
  NM_COLABORADOR VARCHAR(50),
  ID_UNIDADE INT,
  PRIMARY KEY(CD_COLABORADOR),
  CONSTRAINT UNIDADE_FK FOREIGN KEY(ID_UNIDADE)
  REFERENCES TB_UNIDADE(CD_UNIDADE)
);

CREATE TABLE TB_EMPRESTIMO(
  CD_EMPRESTIMO INT AUTO_INCREMENT,
  ID_COLABORADOR INT,
  ID_EXEMPLAR INT,
  DT_EMPRESTIMO DATE,
  DT_LIMITE DATE,
  DT_DEVOLUCAO DATE,
  PRIMARY KEY(CD_EMPRESTIMO),
  CONSTRAINT COLABORADOR_FK FOREIGN KEY(ID_COLABORADOR)
  REFERENCES TB_COLABORADOR(CD_COLABORADOR),
  CONSTRAINT EXEMPLAR_FK FOREIGN KEY(ID_EXEMPLAR)
  REFERENCES TB_EXEMPLAR(CD_EXEMPLAR)
);

CREATE TABLE TB_RESERVA(
  CD_RESERVA INT AUTO_INCREMENT,
  ID_COLABORADOR INT,
  ID_PUBLICACAO INT,
  DT_RESERVA TIMESTAMP,
  ATIVA TINYINT(1),
  PRIMARY KEY(CD_RESERVA),
  CONSTRAINT COLABORADORR_FK FOREIGN KEY(ID_COLABORADOR)
  REFERENCES TB_COLABORADOR(CD_COLABORADOR),
  CONSTRAINT PUBLICACAOO_FK FOREIGN KEY(ID_PUBLICACAO)
  REFERENCES TB_PUBLICACAO(CD_PUBLICACAO)
);

CREATE TABLE TB_AUTOR(
  CD_AUTOR INT AUTO_INCREMENT,
  NM_AUTOR VARCHAR(50),
  PRIMARY KEY(CD_AUTOR)
);

CREATE TABLE TB_ASSUNTO(
  CD_ASSUNTO INT AUTO_INCREMENT,
  NM_ASSUNTO VARCHAR(50),
  PRIMARY KEY(CD_ASSUNTO)
);

CREATE TABLE PUB_ASSUNTO(
  ID_ASSUNTO INT,
  ID_PUBLICACAO INT,
  PRIMARY KEY(ID_ASSUNTO, ID_PUBLICACAO),
  CONSTRAINT ASSUNTO_FK FOREIGN KEY(ID_ASSUNTO)
  REFERENCES TB_ASSUNTO(CD_ASSUNTO),
  CONSTRAINT PUBLICACAOOO_FK FOREIGN KEY(ID_PUBLICACAO)
  REFERENCES TB_PUBLICACAO(CD_PUBLICACAO)
);

CREATE TABLE PUB_AUTOR(
  ID_PUBLICACAO INT,
  ID_AUTOR INT,
  PRIMARY KEY(ID_PUBLICACAO, ID_AUTOR),
  CONSTRAINT PUBLICACAOOOO_FK FOREIGN KEY(ID_PUBLICACAO)
  REFERENCES TB_PUBLICACAO(CD_PUBLICACAO),
  CONSTRAINT AUTOR_FK FOREIGN KEY(ID_AUTOR)
  REFERENCES TB_AUTOR(CD_AUTOR)
);