-- CONSULTA DE DADOS EM 2 OU  + TABLES
SELECT * FROM COUNTRY;
SELECT * FROM COUNTRYLANGUAGE;
SELECT * FROM CITY;

-- resolvendo ambiguidade quando existem campos com o mesmo nome
-- em tabelas diferentes na mesma consulta
SELECT 
COUNTRYLANGUAGE.COUNTRYCODE,
COUNTRY.NAME,
CITY.NAME,
LANGUAGE, 
ISOFFICIAL,
PERCENTAGE
FROM COUNTRYLANGUAGE, COUNTRY, CITY
WHERE
COUNTRYLANGUAGE.COUNTRYCODE = CODE AND
CITY.COUNTRYCODE = CODE;

-- criar "apelido - ALIÁS" para encurtar nomes de tables
SELECT 
CL.COUNTRYCODE,
CO.NAME PAÍS,
CI.NAME CIDADE,
LANGUAGE, 
ISOFFICIAL,
PERCENTAGE
FROM 
COUNTRYLANGUAGE AS CL, COUNTRY AS CO, CITY CI
WHERE
CL.COUNTRYCODE = CODE AND
CI.COUNTRYCODE = CODE;